// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD301mJsW7m03bQYurURnLb8WfI7ih6XEY',
    appId: '1:192557374671:web:7602bec009f98f660c2bba',
    messagingSenderId: '192557374671',
    projectId: 'myapp-9ef2f',
    authDomain: 'myapp-9ef2f.firebaseapp.com',
    storageBucket: 'myapp-9ef2f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn7OcNXQbAHYdGEaPWKOuCoDni4BiB014',
    appId: '1:192557374671:android:64382797f12684ef0c2bba',
    messagingSenderId: '192557374671',
    projectId: 'myapp-9ef2f',
    storageBucket: 'myapp-9ef2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP58fN6HZc3RajcX214VP2sJSN6FBcDMM',
    appId: '1:192557374671:ios:e73d1f1adb1c1d5e0c2bba',
    messagingSenderId: '192557374671',
    projectId: 'myapp-9ef2f',
    storageBucket: 'myapp-9ef2f.appspot.com',
    iosClientId: '192557374671-os375dsotumnn6rgqbq86lh54d184v1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP58fN6HZc3RajcX214VP2sJSN6FBcDMM',
    appId: '1:192557374671:ios:e73d1f1adb1c1d5e0c2bba',
    messagingSenderId: '192557374671',
    projectId: 'myapp-9ef2f',
    storageBucket: 'myapp-9ef2f.appspot.com',
    iosClientId: '192557374671-os375dsotumnn6rgqbq86lh54d184v1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );
}
